apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: php
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pvc-volume
  labels:
    type: local
spec:
  storageClassName: php
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/tema2/memorie/vol1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: php
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
            storage: 3Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pvc-volume
  labels:
    type: local
spec:
  storageClassName: php
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/tema2/memorie/vol2"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-pv-claim
  labels:
    app: chat
spec:
  storageClassName: php
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: couchdb-pvc-volume
  labels:
    type: local
spec:
  storageClassName: php
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
